### ISSUE TITLE
Cannot read properties of undefined (reading 'some') when data model has two array models

### ISSUE THREAD

**Issue by KardonskyRoman** [vaadin/hilla#1491]
### Describe the bug

This is the java data model:
```java
public class Project {

    private List<Declarant> declarants;

    protected List<String> cadastralNumber;

    public List<Declarant> getDeclarants() {
        if (declarants == null) {
            declarants = new ArrayList<Declarant>();
        }
        return this.declarants;
    }

    public List<String> getCadastralNumber() {
        if (cadastralNumber == null) {
            cadastralNumber = new ArrayList<String>();
        }
        return this.cadastralNumber;
    }

}
```

This is 'add button' for declarants:
```ts
 <vaadin-button
        @click=${() => {
          if (!this.binder.value.declarants) {
            this.binder.value.declarants = [];
          }
          this.binder.for(this.binder.model.declarants).appendItem();
          this.requestUpdate();
        }}
      >
        Add declarant
      </vaadin-button>
```

This is 'add button' for cadastralNumber:
```ts
<vaadin-button
        @click=${() => {
          if (!this.binder.value.cadastralNumber) {
            this.binder.value.cadastralNumber = [];
          }
          this.binder.for(this.binder.model.cadastralNumber).appendItem();
          this.requestUpdate();
        }}
      >
        Add number
      </vaadin-button>
````
Both buttons works fine by themselves. 
If you press (page should be reloaded) 'Add number'->'Add declarant' - it works fine
If you press (page should be reloaded) 'Add declarant'->'Add number' - it fails with error:
```
Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[HelloWorldView.update()]' TypeError: Cannot read properties of undefined (reading 'some')
    at get required [as required] (BinderNode.ts:250:30)
    at Directive.update (Field.ts:419:15)
    at Directive._$resolve (directive.js:42:1)
    at resolveDirective (lit-html.js:660:1)
    at PropertyPart._$setValue (lit-html.js:1162:1)
    at TemplateInstance._update (lit-html.js:741:1)
    at ChildPart._commitTemplateResult (lit-html.js:1002:1)
    at ChildPart._$setValue (lit-html.js:851:1)
    at ChildPart._commitIterable (lit-html.js:1056:1)
    at ChildPart._$setValue (lit-html.js:863:1)
```

### Expected-behavior

both buttons should work pressing in any order

### Reproduction

https://github.com/KardonskyRoman/hilla_test
build->run-> open hello world-> press 'add declarant' -> press 'add number'

### System Info

Hilla 2.2.1

**Comment by KardonskyRoman** [comment]
Hilla 2.2.0 has throws same error
