### ISSUE TITLE
Undefined exception while clearing form with array model with nested keys

### ISSUE THREAD

**Issue by KardonskyRoman** [vaadin/hilla#1565]
### Describe the bug

Clearing form via `this.binder.clear()` throws an exception:
```
Uncaught TypeError: Cannot use 'in' operator to search for '0' in undefined
    at get defaultValue [as defaultValue] (BinderNode.ts:179:33)
    at B2.getChildBinderNodes (BinderNode.ts:403:16)
    at getChildBinderNodes.next (<anonymous>)
    at B2.clearValidation (BinderNode.ts:354:18)
    at BinderNode.ts:354:85
    at Array.filter (<anonymous>)
    at B2.clearValidation (BinderNode.ts:354:41)
    at BinderNode.ts:354:85
    at Array.filter (<anonymous>)
    at d4.clearValidation (BinderNode.ts:354:41)
```

### Expected-behavior

`this.binder.clear()` should work without errors

### Reproduction

https://github.com/KardonskyRoman/hilla_test
build-> run-> go HelloWorld view -> click 'Add declarant' -> click 'Clear form' -> catch the error

### System Info

Hilla 2.2.2

**Comment by platosha** [comment]
Thanks for reporting with the reproduction. I can reproduce the issue with the provided application.
