### ISSUE TITLE
Hill project is not starting and getting error:java.lang.StringIndexOutOfBoundsException: begin 0, end -

### ISSUE THREAD

**Issue by imran-momin4041** [vaadin/hilla#1704]
### Describe the bug

Facing Java path issue in hilla project which downloaded from [start.vaadin.com](https://start.vaadin.com)
![bug](https://github.com/vaadin/hilla/assets/39003300/ef931d57-ce55-4676-b0bd-1872c53922a2)

### Reproduction

Download project and run it 

### System Info

Eclipse :Version: 2022-09 (4.25.0)
Os: Windows 11

**Comment by marcushellberg** [comment]
Can you please attach the entire log, or at least the complete exception to help us look into this?

**Comment by Legioth** [comment]
Could also be useful if you could put a breakpoint in that method to see what value `javaExecPath` has when the problem occurs.

Also: what JDK are you using and how do you launch the application?

**Comment by Tbusk** [comment]
Hi @marcushellberg and @Legioth . I am getting the same error on my two Windows 11 PCs with openjdk 17.0.9 installed, running with the default 'run as java application' option using Eclipse.  I can reproduce this error every time I try to use eclipse with Hilla.  Let me know if you need any additional information. 

```Java
... skipping to here
2023-11-14T07:28:46.938-05:00  INFO 3444 --- [  restartedMain] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2023-11-14T07:28:47.000-05:00  INFO 3444 --- [  restartedMain] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.2.13.Final
2023-11-14T07:28:47.003-05:00  INFO 3444 --- [  restartedMain] org.hibernate.cfg.Environment            : HHH000406: Using bytecode reflection optimizer
2023-11-14T07:28:47.254-05:00  INFO 3444 --- [  restartedMain] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
2023-11-14T07:28:48.045-05:00  INFO 3444 --- [  restartedMain] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000489: No JTA platform available (set 'hibernate.transaction.jta.platform' to enable JTA platform integration)
2023-11-14T07:28:48.073-05:00  INFO 3444 --- [  restartedMain] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2023-11-14T07:28:48.130-05:00  WARN 3444 --- [  restartedMain] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2023-11-14T07:28:48.507-05:00  INFO 3444 --- [  restartedMain] o.s.d.j.r.query.QueryEnhancerFactory     : Hibernate is in classpath; If applicable, HQL parser will be used.
2023-11-14T07:28:48.831-05:00  INFO 3444 --- [  restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2023-11-14T07:28:50.549-05:00  INFO 3444 --- [  restartedMain] c.v.f.s.DefaultDeploymentConfiguration   : 
Vaadin is running in DEVELOPMENT mode - do not use for production deployments.
2023-11-14T07:28:50.574-05:00  INFO 3444 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2023-11-14T07:28:50.579-05:00  INFO 3444 --- [  restartedMain] com.example.application.Application      : Started Application in 6.888 seconds (process running for 7.39)
2023-11-14T07:28:50.987-05:00  INFO 3444 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2023-11-14T07:28:50.988-05:00  INFO 3444 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2023-11-14T07:28:50.988-05:00  INFO 3444 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 0 ms
2023-11-14T07:28:51.055-05:00  INFO 3444 --- [nio-8080-exec-1] c.vaadin.flow.spring.SpringInstantiator  : The number of beans implementing 'I18NProvider' is 0. Cannot use Spring beans for I18N, falling back to the default behavior
2023-11-14T07:28:51.056-05:00 ERROR 3444 --- [nio-8080-exec-1] c.v.flow.server.DefaultErrorHandler      : 

java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 127
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606) ~[na:na]
	at java.base/java.lang.String.substring(String.java:2709) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.lambda$getCurrentJavaProcessJavaHome$2(CommandRunner.java:208) ~[engine-core-2.3.3.jar:na]
	at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.getCurrentJavaProcessJavaHome(CommandRunner.java:206) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.environment(CommandRunner.java:226) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.createProcessBuilder(CommandRunner.java:174) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.executeCommand(CommandRunner.java:118) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.executeWithTestArguments(CommandRunner.java:85) ~[engine-core-2.3.3.jar:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[na:na]
	at java.base/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.run(CommandRunner.java:71) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.internal.AbstractTaskEndpointGenerator.prepareEngineConfiguration(AbstractTaskEndpointGenerator.java:87) ~[engine-runtime-2.3.3.jar:na]
	at dev.hilla.internal.AbstractTaskEndpointGenerator.getEngineConfiguration(AbstractTaskEndpointGenerator.java:59) ~[engine-runtime-2.3.3.jar:na]
	at dev.hilla.internal.TaskGenerateOpenAPIImpl.execute(TaskGenerateOpenAPIImpl.java:73) ~[engine-runtime-2.3.3.jar:na]
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:312) ~[flow-server-24.2.2.jar:24.2.2]
	at com.vaadin.base.devserver.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:352) ~[vaadin-dev-server-24.2.2.jar:na]
	at com.vaadin.base.devserver.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:293) ~[vaadin-dev-server-24.2.2.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]

2023-11-14T07:28:51.060-05:00 ERROR 3444 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[springServlet]        : Servlet.service() for servlet [springServlet] threw exception

java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 127
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606) ~[na:na]
	at java.base/java.lang.String.substring(String.java:2709) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.lambda$getCurrentJavaProcessJavaHome$2(CommandRunner.java:208) ~[engine-core-2.3.3.jar:na]
	at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.getCurrentJavaProcessJavaHome(CommandRunner.java:206) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.environment(CommandRunner.java:226) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.createProcessBuilder(CommandRunner.java:174) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.executeCommand(CommandRunner.java:118) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.executeWithTestArguments(CommandRunner.java:85) ~[engine-core-2.3.3.jar:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[na:na]
	at java.base/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.run(CommandRunner.java:71) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.internal.AbstractTaskEndpointGenerator.prepareEngineConfiguration(AbstractTaskEndpointGenerator.java:87) ~[engine-runtime-2.3.3.jar:na]
	at dev.hilla.internal.AbstractTaskEndpointGenerator.getEngineConfiguration(AbstractTaskEndpointGenerator.java:59) ~[engine-runtime-2.3.3.jar:na]
	at dev.hilla.internal.TaskGenerateOpenAPIImpl.execute(TaskGenerateOpenAPIImpl.java:73) ~[engine-runtime-2.3.3.jar:na]
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:312) ~[flow-server-24.2.2.jar:24.2.2]
	at com.vaadin.base.devserver.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:352) ~[vaadin-dev-server-24.2.2.jar:na]
	at com.vaadin.base.devserver.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:293) ~[vaadin-dev-server-24.2.2.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]

2023-11-14T07:28:51.061-05:00 ERROR 3444 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [com.vaadin.flow.server.ServiceException: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 127] with root cause

java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 127
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606) ~[na:na]
	at java.base/java.lang.String.substring(String.java:2709) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.lambda$getCurrentJavaProcessJavaHome$2(CommandRunner.java:208) ~[engine-core-2.3.3.jar:na]
	at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.getCurrentJavaProcessJavaHome(CommandRunner.java:206) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.environment(CommandRunner.java:226) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.createProcessBuilder(CommandRunner.java:174) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.executeCommand(CommandRunner.java:118) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.executeWithTestArguments(CommandRunner.java:85) ~[engine-core-2.3.3.jar:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[na:na]
	at java.base/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.run(CommandRunner.java:71) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.internal.AbstractTaskEndpointGenerator.prepareEngineConfiguration(AbstractTaskEndpointGenerator.java:87) ~[engine-runtime-2.3.3.jar:na]
	at dev.hilla.internal.AbstractTaskEndpointGenerator.getEngineConfiguration(AbstractTaskEndpointGenerator.java:59) ~[engine-runtime-2.3.3.jar:na]
	at dev.hilla.internal.TaskGenerateOpenAPIImpl.execute(TaskGenerateOpenAPIImpl.java:73) ~[engine-runtime-2.3.3.jar:na]
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:312) ~[flow-server-24.2.2.jar:24.2.2]
	at com.vaadin.base.devserver.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:352) ~[vaadin-dev-server-24.2.2.jar:na]
	at com.vaadin.base.devserver.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:293) ~[vaadin-dev-server-24.2.2.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]

2023-11-14T07:28:51.126-05:00 ERROR 3444 --- [nio-8080-exec-2] c.v.flow.server.DefaultErrorHandler      : 

java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 127
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606) ~[na:na]
	at java.base/java.lang.String.substring(String.java:2709) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.lambda$getCurrentJavaProcessJavaHome$2(CommandRunner.java:208) ~[engine-core-2.3.3.jar:na]
	at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.getCurrentJavaProcessJavaHome(CommandRunner.java:206) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.environment(CommandRunner.java:226) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.createProcessBuilder(CommandRunner.java:174) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.executeCommand(CommandRunner.java:118) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.executeWithTestArguments(CommandRunner.java:85) ~[engine-core-2.3.3.jar:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[na:na]
	at java.base/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.run(CommandRunner.java:71) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.internal.AbstractTaskEndpointGenerator.prepareEngineConfiguration(AbstractTaskEndpointGenerator.java:87) ~[engine-runtime-2.3.3.jar:na]
	at dev.hilla.internal.AbstractTaskEndpointGenerator.getEngineConfiguration(AbstractTaskEndpointGenerator.java:59) ~[engine-runtime-2.3.3.jar:na]
	at dev.hilla.internal.TaskGenerateOpenAPIImpl.execute(TaskGenerateOpenAPIImpl.java:73) ~[engine-runtime-2.3.3.jar:na]
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:312) ~[flow-server-24.2.2.jar:24.2.2]
	at com.vaadin.base.devserver.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:352) ~[vaadin-dev-server-24.2.2.jar:na]
	at com.vaadin.base.devserver.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:293) ~[vaadin-dev-server-24.2.2.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]

2023-11-14T07:28:51.127-05:00 ERROR 3444 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[springServlet]        : Servlet.service() for servlet [springServlet] threw exception

java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 127
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606) ~[na:na]
	at java.base/java.lang.String.substring(String.java:2709) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.lambda$getCurrentJavaProcessJavaHome$2(CommandRunner.java:208) ~[engine-core-2.3.3.jar:na]
	at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.getCurrentJavaProcessJavaHome(CommandRunner.java:206) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.environment(CommandRunner.java:226) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.createProcessBuilder(CommandRunner.java:174) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.executeCommand(CommandRunner.java:118) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.executeWithTestArguments(CommandRunner.java:85) ~[engine-core-2.3.3.jar:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[na:na]
	at java.base/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.run(CommandRunner.java:71) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.internal.AbstractTaskEndpointGenerator.prepareEngineConfiguration(AbstractTaskEndpointGenerator.java:87) ~[engine-runtime-2.3.3.jar:na]
	at dev.hilla.internal.AbstractTaskEndpointGenerator.getEngineConfiguration(AbstractTaskEndpointGenerator.java:59) ~[engine-runtime-2.3.3.jar:na]
	at dev.hilla.internal.TaskGenerateOpenAPIImpl.execute(TaskGenerateOpenAPIImpl.java:73) ~[engine-runtime-2.3.3.jar:na]
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:312) ~[flow-server-24.2.2.jar:24.2.2]
	at com.vaadin.base.devserver.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:352) ~[vaadin-dev-server-24.2.2.jar:na]
	at com.vaadin.base.devserver.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:293) ~[vaadin-dev-server-24.2.2.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]

2023-11-14T07:28:51.128-05:00 ERROR 3444 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [com.vaadin.flow.server.ServiceException: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 127] with root cause

java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 127
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606) ~[na:na]
	at java.base/java.lang.String.substring(String.java:2709) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.lambda$getCurrentJavaProcessJavaHome$2(CommandRunner.java:208) ~[engine-core-2.3.3.jar:na]
	at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.getCurrentJavaProcessJavaHome(CommandRunner.java:206) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.environment(CommandRunner.java:226) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.createProcessBuilder(CommandRunner.java:174) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.executeCommand(CommandRunner.java:118) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.engine.commandrunner.CommandRunner.executeWithTestArguments(CommandRunner.java:85) ~[engine-core-2.3.3.jar:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[na:na]
	at java.base/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:706) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[na:na]
	at dev.hilla.engine.commandrunner.CommandRunner.run(CommandRunner.java:71) ~[engine-core-2.3.3.jar:na]
	at dev.hilla.internal.AbstractTaskEndpointGenerator.prepareEngineConfiguration(AbstractTaskEndpointGenerator.java:87) ~[engine-runtime-2.3.3.jar:na]
	at dev.hilla.internal.AbstractTaskEndpointGenerator.getEngineConfiguration(AbstractTaskEndpointGenerator.java:59) ~[engine-runtime-2.3.3.jar:na]
	at dev.hilla.internal.TaskGenerateOpenAPIImpl.execute(TaskGenerateOpenAPIImpl.java:73) ~[engine-runtime-2.3.3.jar:na]
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:312) ~[flow-server-24.2.2.jar:24.2.2]
	at com.vaadin.base.devserver.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:352) ~[vaadin-dev-server-24.2.2.jar:na]
	at com.vaadin.base.devserver.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:293) ~[vaadin-dev-server-24.2.2.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]
```

**Comment by mcollovati** [comment]
It could be that the executable in Windows is `javaw.exe`

Take a look at this test in `vaadin-dev-server` module, that inspects the process chain for Eclipse on Windows

https://github.com/vaadin/flow/blob/1968bedbbd958964a0fa163958550811d8a94739/vaadin-dev-server/src/test/java/com/vaadin/base/devserver/OpenInCurrentIdeTest.java#L371-L376
