### ISSUE TITLE
Binder.clear() throws an error after array data model got appendItem()

### ISSUE THREAD

**Issue by KardonskyRoman** [vaadin/hilla#1834]
### Describe the bug

This code
```ts
this.binder.clear();
``` 
throws en error:

```shell
Uncaught TypeError: Cannot use 'in' operator to search for '0' in undefined
    at get defaultValue [as defaultValue] (BinderNode.ts:179:33)
    at B2.getChildBinderNodes (BinderNode.ts:403:16)
    at getChildBinderNodes.next (<anonymous>)
    at B2.clearValidation (BinderNode.ts:354:18)
    at BinderNode.ts:354:85
    at Array.filter (<anonymous>)
    at B2.clearValidation (BinderNode.ts:354:41)
    at BinderNode.ts:354:85
    at Array.filter (<anonymous>)
    at d4.clearValidation (BinderNode.ts:354:41)
```

Reproduction is below

### Expected-behavior

binder.clear() should work without errors

### Reproduction

https://github.com/KardonskyRoman/hilla_test
Build->Run->Go to HelloWorld View-> click button 'Add declarant' -> click button 'Clear from' -> catch the error.

### System Info

hilla 2.2.2, 2.3.2

**Comment by KardonskyRoman** [comment]
In hilla 2.4.0 it works perfect.
