### ISSUE TITLE
PiT 24.4: Error URI is not hierarchical when moving `frontend` folder

### ISSUE THREAD

**Issue by manolo** [vaadin/hilla#2203]
### Description of the bug

When I move my `frontend` folder to `src/main` I get the exception

```
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.base/java.io.File.<init>(File.java:420) ~[na:na]
	at com.vaadin.hilla.startup.RouteUnifyingServiceInitListener.registerClientRoutes(RouteUnifyingServiceInitListener.java:80) ~[hilla-endpoint-24.4.0.alpha11.jar!/:na]
	at com.vaadin.hilla.startup.RouteUnifyingServiceInitListener.serviceInit(RouteUnifyingServiceInitListener.java:70) ~[hilla-endpoint-24.4.0.alpha11.jar!/:na]
	at com.vaadin.flow.server.VaadinService.lambda$init$0(VaadinService.java:236) ~[flow-server-24.4.0.alpha18.jar!/:24.4.0.alpha18]
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[na:na]
```

### Expected behavior

Project works

### Minimal reproducible example

```
# Create an app in start with html templates
   curl -s -f 'https://start.vaadin.com/dl?&preset=latest-javahtml&projectName=latest-javahtml' -o latest-javahtml.zip
   unzip latest-javahtml.zip
   cd latest-javahtml

# Bump version
   perl -0777 -pi -e 's|(<vaadin.version>)([^\s]+)(</vaadin.version>)|${1}24.4.0.alpha10${3}|g' pom.xml

# Add pre-releases repos
   perl -pi -e 's|(\s*)(<repositories>)|$1$2\n$1$1<repository><id>v</id><url>https://maven.vaadin.com/vaadin-prereleases</url></repository>|' pom.xml
   perl -pi -e 's|(\s*)(</properties>)|$1$2\n$1<pluginRepositories><pluginRepository><id>v</id><url>https://maven.vaadin.com/vaadin-prereleases</url></pluginRepository></pluginRepositories>|' pom.xml

# Move frontend folder 
   mv frontend src/main/frontend

# Build the application
   ./mvnw -ntp -B -Pproduction package  -Dmaven.compiler.showDeprecation 
```

### Versions

- Vaadin / Flow version: 24.4.0.alpha10

**Comment by manolo** [comment]
Seems not a problem only when moving the folder, at least this project is also failing in production mode with the frontend in the root folder

```
git clone git@github.com:vaadin/flow-hilla-hybrid-example.git
cd flow-hilla-hybrid-example
git checkout v24.4.0.alpha11 
./mvnw -B package -Pproduction
java -jar target/*.jar
```
