### ISSUE TITLE
Duplicate key detected in ClientRouteRegistry

### ISSUE THREAD

**Issue by mshabarov** [vaadin/hilla#2329]
### Describe the bug

I randomly get the runtime exception about duplicate key when Hilla tries to get all routes from `ClientRouteRegistry`:

```
java.lang.IllegalArgumentException: duplicate key: /about
        at java.base/java.util.ImmutableCollections$MapN.<init>(ImmutableCollections.java:1196) ~[na:na]
        at java.base/java.util.Map.ofEntries(Map.java:1680) ~[na:na]
        at java.base/java.util.Map.copyOf(Map.java:1748) ~[na:na]
        at com.vaadin.hilla.route.ClientRouteRegistry.getAllRoutes(ClientRouteRegistry.java:67) ~[hilla-endpoint-24.4.0.alpha21.jar:na]
        at com.vaadin.hilla.route.RouteUnifyingIndexHtmlRequestListener.collectClientViews(RouteUnifyingIndexHtmlRequestListener.java:115) ~[hilla-endpoint-24.4.0.alpha21.jar:na]
        at com.vaadin.hilla.route.RouteUnifyingIndexHtmlRequestListener.modifyIndexHtmlResponse(RouteUnifyingIndexHtmlRequestListener.java:82) ~[hilla-endpoint-24.4.0.alpha21.jar:na]

```

This prevents application to start.
Happens in both dev and prod modes, but quite randomly.

### Expected-behavior

No duplicates in routes and no exception on startup.

### Reproduction

This can be reproduced with the branch https://github.com/vaadin/flow-hilla-hybrid-example/pull/29.

Download the starter, checkout the branch and start with `mvn` (or in production mode `mvn spring-boot:run -Pproduction`).

Reproduces randomly locally and in GHA. You need to try several times.

### System Info

Vaadin 24.4.0.alpha21, Hilla 24.4.0.alpha21

**Comment by cromoteca** [comment]
@mshabarov do you remember if this happens at startup or when making changes? I haven't been able to see it yet.

**Comment by mshabarov** [comment]
I couldn't reproduce this issue anymore after [removing the legacy views.ts](https://github.com/vaadin/hilla/pull/2320/).
However, it's unclear how this could help.
As we discussed with @taefi , it makes sense to:
- use `ConcurrentHashMap` or such for `registeredRoutes` in `ClientRouteRegistry` or better 
- use `synchronized` for `registerClientRoutes` in `RouteUnifyingIndexHtmlRequestListener` and set `lastUpdated` as `volatile`, which makes it visible and eliminates registering routes concurrently.

**Comment by mshabarov** [comment]
> @mshabarov do you remember if this happens at startup or when making changes? I haven't been able to see it yet.

it happened to me in different two cases:
- when starting an app in dev mode with `mvn`
- when running IT tests in prod mode with `mvn verify -Pit,production`

Also happened several times in GHA when IT were running in prod mode.

**Comment by mshabarov** [comment]
UPD: could reproduce it again with mvn verify -Pit,production

**Comment by cromoteca** [comment]
I can't. Did you update your local branch to include my commit?

**Comment by mshabarov** [comment]
Yes.
