### ISSUE TITLE
NoSuchMethodError when starting 24.4.0.beta3

### ISSUE THREAD

**Issue by whiteancient** [vaadin/hilla#2437]
### Describe the bug

I get this stacktrace every time I start Hilla:

java.lang.NoSuchMethodError: 'void com.sun.jna.Memory.close()'
	at oshi.util.Util.freeMemory(Util.java:83) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.jna.Struct$CloseableSystemInfo.close(Struct.java:166) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.platform.windows.WindowsCentralProcessor.queryProcessorId(WindowsCentralProcessor.java:130) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.util.Memoizer$1.get(Memoizer.java:61) ~[oshi-core-6.4.10.jar:6.4.10]
	at oshi.hardware.common.AbstractCentralProcessor.getProcessorIdentifier(AbstractCentralProcessor.java:109) ~[oshi-core-6.4.10.jar:6.4.10]
	at com.vaadin.pro.licensechecker.MachineId.getComputerId(MachineId.java:38) ~[license-checker-1.12.12.jar:1.12.12]
	at com.vaadin.pro.licensechecker.MachineId.get(MachineId.java:19) ~[license-checker-1.12.12.jar:1.12.12]
	at com.vaadin.copilot.analytics.AnalyticsClient.<init>(AnalyticsClient.java:34) ~[copilot-24.4.0.beta3.jar:na]
	at com.vaadin.copilot.Copilot.handleConnect(Copilot.java:61) ~[copilot-24.4.0.beta3.jar:na]
	at com.vaadin.base.devserver.DebugWindowConnection.handleConnect(DebugWindowConnection.java:207) ~[vaadin-dev-server-24.4.0.beta3.jar:na]
	at com.vaadin.base.devserver.DebugWindowConnection.onConnect(DebugWindowConnection.java:187) ~[vaadin-dev-server-24.4.0.beta3.jar:na]
	at com.vaadin.flow.server.communication.PushHandler.lambda$onConnect$3(PushHandler.java:605) ~[flow-server-24.4.0.beta3.jar:24.4.0.beta3]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
	at com.vaadin.flow.server.communication.PushHandler.lambda$onConnect$4(PushHandler.java:604) ~[flow-server-24.4.0.beta3.jar:24.4.0.beta3]
	at com.vaadin.flow.server.communication.PushHandler.callWithServiceAndSession(PushHandler.java:227) ~[flow-server-24.4.0.beta3.jar:24.4.0.beta3]
	at com.vaadin.flow.server.communication.PushHandler.onConnect(PushHandler.java:601) ~[flow-server-24.4.0.beta3.jar:24.4.0.beta3]
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onConnect(PushAtmosphereHandler.java:103) ~[flow-server-24.4.0.beta3.jar:24.4.0.beta3]
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77) ~[flow-server-24.4.0.beta3.jar:24.4.0.beta3]
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:217) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:103) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2284) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:574) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:213) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:254) ~[atmosphere-runtime-3.0.5.slf4jvaadin1.jar:3.0.5.slf4jvaadin1]
	at org.eclipse.jetty.ee10.websocket.jakarta.common.JakartaWebSocketFrameHandler.onOpen(JakartaWebSocketFrameHandler.java:175) ~[jetty-ee10-websocket-jakarta-common-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.websocket.core.WebSocketCoreSession.lambda$onOpen$6(WebSocketCoreSession.java:400) ~[jetty-websocket-core-common-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1298) ~[jetty-server-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.run(ContextHandler.java:1285) ~[jetty-server-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker$1.handle(AbstractHandshaker.java:179) ~[jetty-websocket-core-server-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.websocket.core.WebSocketCoreSession.onOpen(WebSocketCoreSession.java:400) ~[jetty-websocket-core-common-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.websocket.core.WebSocketConnection.onOpen(WebSocketConnection.java:531) ~[jetty-websocket-core-common-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:435) ~[jetty-io-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.server.internal.HttpConnection$HttpStreamOverHTTP1.succeeded(HttpConnection.java:1518) ~[jetty-server-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.server.HttpStream$Wrapper.succeeded(HttpStream.java:221) ~[jetty-server-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.server.internal.CompletionStreamWrapper.succeeded(CompletionStreamWrapper.java:45) ~[jetty-server-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.server.HttpStream$Wrapper.succeeded(HttpStream.java:221) ~[jetty-server-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.session.AbstractSessionManager$SessionStreamWrapper.succeeded(AbstractSessionManager.java:1468) ~[jetty-session-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.completeStream(HttpChannelState.java:728) ~[jetty-server-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:654) ~[jetty-server-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:411) ~[jetty-server-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322) ~[jetty-io-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99) ~[jetty-io-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[jetty-io-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478) ~[jetty-util-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441) ~[jetty-util-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293) ~[jetty-util-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201) ~[jetty-util-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311) ~[jetty-util-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979) ~[jetty-util-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209) ~[jetty-util-12.0.8.jar:12.0.8]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164) ~[jetty-util-12.0.8.jar:12.0.8]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

Everything seems to work as expected though.

### Expected-behavior

No Error

### Reproduction

Start the server

### System Info

Windows 11, 
Hilla 24.4.0.beta3
Java: Jetbrains jbrsdk_jcef-21.0.2-windows-x64-b375.1

**Comment by whiteancient** [comment]
Was a transitive dependency from Scala 3.4.0 that was overriding the Hilla dep on net.java.dev.jna.
