### ISSUE TITLE
Starting an app using remote debug options causes the app not to start

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#2464]
### Describe the bug

```
npx @hilla/cli init --pre hilla-debug
cd hilla-debug
MAVEN_OPTS="-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=4000,suspend=n" mvn
```

causes
```
java.lang.IllegalStateException: com.vaadin.flow.server.ExecutionFailedException: Failed to configure Hilla engine: no runner succeeded. Set log level to debug to see more details.
	at com.vaadin.base.devserver.AbstractDevServerRunner.getCause(AbstractDevServerRunner.java:772) ~[vaadin-dev-server-24.4.0.beta5.jar:na]
	at com.vaadin.base.devserver.AbstractDevServerRunner.getCause(AbstractDevServerRunner.java:768) ~[vaadin-dev-server-24.4.0.beta5.jar:na]
	at com.vaadin.base.devserver.AbstractDevServerRunner.handleRequestInternal(AbstractDevServerRunner.java:631) ~[vaadin-dev-server-24.4.0.beta5.jar:na]
	at com.vaadin.base.devserver.AbstractDevServerRunner.handleRequest(AbstractDevServerRunner.java:617) ~[vaadin-dev-server-24.4.0.beta5.jar:na]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1584) ~[flow-server-24.4.0.beta5.jar:24.4.0.beta5]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:398) ~[flow-server-24.4.0.beta5.jar:24.4.0.beta5]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106) ~[vaadin-spring-24.4.0.beta5.jar:na]
```

Setting the log level for `com.vaadin.hilla.internal.AbstractTaskEndpointGenerator` in the project logs no additional info

### Expected-behavior

It starts

### Reproduction

above

### System Info

24.4 beta4

**Comment by cromoteca** [comment]
The `mvn` command run by Hilla is probably inheriting `MAVEN_OPTS`. We should probably clear it when running Maven.

**Comment by cromoteca** [comment]
That can still be a problem if you want to debug on a Docker container for example.
