### ISSUE TITLE
Hilla app with @PWA annotation fails when running as native compiled image 

### ISSUE THREAD

**Issue by rbrki07** [vaadin/hilla#2496]
### Describe the bug

A Hilla app with `@PWA` annotation throws an exception when running as native compiled image:

```
java.lang.UnsatisfiedLinkError: No awt in java.library.path
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:136) ~[na:na]
```

### Expected-behavior

A Hilla app with `@PWA` annotation should not throw unexpected exceptions when running as native compiled image.

### Reproduction

Create a new Hilla project:
```
npx @hilla/cli@latest init --next hilla-native-pwa
```

Add `@PWA(name = "Hilla PWA", shortName = "PWA")` to `src/main/java/com/example/application/Application.java`.

Compile Hilla app to native image:
```
./mvnw clean package -Pproduction -Pnative native:compile
```

Run Hilla app as native compiled image:
```
./target/hilla-native-pwa
```

### System Info

Hilla: 24.4.0.beta5
Hilla CLI: 2.0.1
Java: 21.0.2 (OpenJDK Runtime Environment GraalVM CE 21.0.2+13.1 - build 21.0.2+13-jvmci-23.1-b30)
OS: macOS Sonoma 14.4.1 (23E224)

**Comment by mcollovati** [comment]
vaadin/flow#19457 should fix the issue, but it is not yet released.
You can try it out with 24.4-SNAPSHOT

**Comment by rbrki07** [comment]
Thank you for the reference @mcollovati. I'll give it a try.

**Comment by rbrki07** [comment]
I forked `vaadin/flow`, did `mvn clean install -DskipTests` in the fork, and then I added `flow-server` with version `24.5-SNAPSHOT` in the pom.xml of the project `hilla-native-pwa`:
```
    <dependencies>
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>flow-server</artifactId>
            <version>24.5-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin</artifactId>
        </dependency>
      ...
```

After that, I created the native image again:
```
./mvnw clean package -Pproduction -Pnative native:compile
```
And then started it again:
```
./target/hilla-native-pwa
```
Now there is another error:
```
2024-06-01T12:01:38.281+02:00 ERROR 20447 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Servlet execution threw an exception] with root cause

java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO
        at com.vaadin.flow.server.PwaRegistry.getBaseImage(PwaRegistry.java:369) ~[na:na]
```

**Comment by mcollovati** [comment]
The fix is in the vaadin-spring artifact

**Comment by mcollovati** [comment]
BTW, there should alsobbe a first alpha for Vaadin 24.5 that you can try without having to build flow locally

**Comment by mcollovati** [comment]
Also, if you are want to build flow locally but use Vaadin platform 24.4, maybe better build from the 24.4 branch instead of main

**Comment by rbrki07** [comment]
Alright, obviously I was on the wrong path 😅 Thanks for your advice, you seem to know your repos, modules, artefacts and versions 👍 I'll give it another try later.

**Comment by rbrki07** [comment]
Ok, next try with `24.5.0.alpha1`:
* `npx @hilla/cli@latest init --next hilla-native-pwa`
* Change `vaadin.version` in `pom.xml` to `24.5.0.alpha1`
* Add `@PWA(name = "Hilla PWA", shortName = "PWA")` to `src/main/java/com/example/application/Application.java`
* `./mvnw clean package -Pproduction -Pnative native:compile`
* `./target/hilla-native-pwa`

Error:
```
2024-06-01T16:48:41.927+02:00 ERROR 23332 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[springServlet]        : Servlet.service() for servlet [springServlet] threw exception

java.lang.UnsatisfiedLinkError: No awt in java.library.path
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:136) ~[na:na]
...
2024-06-01T16:48:41.956+02:00 ERROR 23332 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[springServlet]        : Servlet.service() for servlet [springServlet] threw exception

java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO
        at com.vaadin.flow.server.PwaRegistry.getBaseImage(PwaRegistry.java:369) ~[na:na]
...
```

**Comment by mcollovati** [comment]
That's weird. I tried it and it worked for me

**Comment by mcollovati** [comment]
I tested with GraalVM CE 21 and 22, and the native executable works fine with both. No errors at runtime and the application is working. I'm on Linux, I don't know if that makes a difference.

**Comment by mcollovati** [comment]
https://github.com/oracle/graal/issues/4124 could be related

**Comment by rbrki07** [comment]
I can confirm, that I don't get the described errors, when I create the native executable using Linux. I leave it to you @mcollovati to close this ticket or leave it open. Thank you, for your help on this 🫶

**Comment by mcollovati** [comment]
Thanks for testing.
I'll change a bit the title to mention MacOS and transfer the issue to the flow repo for further investigation.
