### ISSUE TITLE
CommandRunner Java Home directory resolve fails on GraalVM Nix OS

### ISSUE THREAD

**Issue by michaelhaessig** [vaadin/hilla#2600]
I'm trying to get a vaadin hilla application to work on [replit.com](https://replit.com/)

The app is starting up, but it fails when it tries to resolve the java home directory:

````java
2024-07-08T06:54:34.389Z ERROR 4565 --- [nio-8080-exec-1] c.v.flow.server.DefaultErrorHandler      : 

java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 81
    at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4604) ~[na:na]
    at java.base/java.lang.String.substring(String.java:2707) ~[na:na]
    at com.vaadin.hilla.engine.commandrunner.CommandRunner.lambda$getCurrentJavaProcessJavaHome$2(CommandRunner.java:230) ~[hilla-engine-core-24.4.2.jar:na]
    at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
    at com.vaadin.hilla.engine.commandrunner.CommandRunner.getCurrentJavaProcessJavaHome(CommandRunner.java:228) ~[hilla-engine-core-24.4.2.jar:na]
````

The default java installation on Replit is using graalvm-ce nix package, it looks like the java executable in the bin directory is using a wrapper **.java-wrapped** as seen in the output of the command:

````java
Optional<String> command = ProcessHandle.current().info().command();
System.out.println("----> Command: " + command.orElse("not available"));
````
![output](https://github.com/vaadin/hilla/assets/1331733/02e2e29d-7c8e-40f6-b8bb-a668483c9066)

![GraalVM bin](https://github.com/vaadin/hilla/assets/1331733/93060386-78aa-4e9d-bf3c-77d360abdf87)

The code on this line is always assuming /bin/java and the fallback to java.home is not working because of the exception:
https://github.com/vaadin/hilla/blob/63cd9088d115beea95d52e087af81b47721bb800/packages/java/engine-core/src/main/java/com/vaadin/hilla/engine/commandrunner/CommandRunner.java#L229

## Suggestions
1. Add != -1 check on "javaExecPath.lastIndexOf(pathToExclude)",  return null.
2. First check for java.home

**Comment by michaelhaessig** [comment]
Closing as Replit turned out to be not really useful for serious java development.  (missing sources and debugging not working)

Github codespaces works much better.
