### ISSUE TITLE
Binding byte[] fields generates an error

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/hilla#396]
### Description of the bug 

When calling `binder.read()` on an object that is based on a Java class that has a `byte[]`, the binding fails with the following error in the browser:
```
Uncaught (in promise) TypeError: array.keys is not a function or its return value is not iterable
    at ArrayModel.[Symbol.iterator] (Models.ts:201:27)
    at ArrayModel.next (<anonymous>)
    at BinderNode.getChildBinderNodes (BinderNode.ts:349:18)
    at getChildBinderNodes.next (<anonymous>)
    at BinderNode.get errors [as errors] (BinderNode.ts:206:40)
    at BinderNode.ts:207:67
    at Array.reduce (<anonymous>)
    at Binder.get errors [as errors] (BinderNode.ts:206:63)
    at Binder.get invalid [as invalid] (BinderNode.ts:224:17)
    at Binder.updateValidation (BinderNode.ts:303:35)
```

### Minimal reproducible example

1. Generate a new Hilla project using `npx @vaadin/cli init --hilla my-hilla-app`
2. Replace the content of `HelloWorldEndpoint.java` to look like the following:
```java
@Endpoint
@AnonymousAllowed
public class HelloWorldEndpoint {

    Foo foo = new Foo();

    public HelloWorldEndpoint() {
        byte[] arr = new byte[20];
        new Random().nextBytes(arr);
        foo.setByteArray(arr);
    }

    @Nonnull
    public Foo loadFoo() {
        return foo;
    }

    class Foo{

        byte[] byteArray;

        public byte[] getByteArray() {
            return byteArray;
        }

        public void setByteArray(byte[] byteArray) {
            this.byteArray = byteArray;
        }
    }
}
```
3. Replace the content `hello-world-view.ts` with:
```ts
@customElement('hello-world-view')
export class HelloWorldView extends View {
  private binder = new Binder(this, FooModel);

  connectedCallback() {
    super.connectedCallback();
  }

  render() {
    return html`
      <vaadin-button @click=${this.fetch}>Fetch from server and read binder</vaadin-button>
    `;
  }

  async fetch() {
    const fromBackend = await HelloWorldEndpoint.loadFoo();
    this.binder.read(fromBackend);
  }
}
```

### Expected behavior
The binding works without an error

### Actual behavior
`binder.read()` generates the noted error

### Versions:
    - Vaadin / Hilla version: 1.0.7
    - Java version: 17
    - OS version: Windows

**Comment by tarekoraby** [comment]
When debugging `Model.ts`, it's obvious that the error is caused by the returned value of the model being a String (instead of an array).

![image](https://user-images.githubusercontent.com/42799254/165510980-4913b063-c9c7-4a01-ab84-d9a4c0eea143.png)
