### ISSUE TITLE
Parent resource not found in the resources when doing a native compile without defining whitelisted packages

### ISSUE THREAD

**Issue by Artur-** [vaadin/hilla#838]
### Description of the bug 
If you create a new Hilla app and remove `vaadin.whitelisted-packages` from `application.properties` and compile it for native as `mvn -Pnative -Pproduction clean package native:compile` then the compiled application will fail to start with
```
java.lang.RuntimeException: Unable to initialize com.vaadin.flow.spring.VaadinServletContextInitializer$VaadinAppShellContextListener
	at com.vaadin.flow.spring.VaadinServletContextInitializer$FailFastServletContextListener.contextInitialized(VaadinServletContextInitializer.java:191) ~[aot-demo:na]
	at com.vaadin.flow.spring.VaadinServletContextInitializer$CompositeServletContextListener.lambda$contextInitialized$0(VaadinServletContextInitializer.java:213) ~[na:na]
	at java.base@19.0.1/java.util.ArrayList.forEach(ArrayList.java:1511) ~[aot-demo:na]
	at com.vaadin.flow.spring.VaadinServletContextInitializer$CompositeServletContextListener.contextInitialized(VaadinServletContextInitializer.java:213) ~[na:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4710) ~[aot-demo:10.1.5]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5155) ~[aot-demo:10.1.5]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[aot-demo:10.1.5]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393) ~[na:na]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1383) ~[na:na]
	at java.base@19.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[aot-demo:na]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[na:na]
	at java.base@19.0.1/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145) ~[aot-demo:na]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916) ~[aot-demo:10.1.5]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:886) ~[na:na]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[aot-demo:10.1.5]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1393) ~[na:na]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1383) ~[na:na]
	at java.base@19.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[aot-demo:na]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[na:na]
	at java.base@19.0.1/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145) ~[aot-demo:na]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:916) ~[aot-demo:10.1.5]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:252) ~[na:na]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[aot-demo:10.1.5]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:430) ~[na:na]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[aot-demo:10.1.5]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:926) ~[na:na]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[aot-demo:10.1.5]
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:485) ~[na:na]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123) ~[na:na]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:104) ~[na:na]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:488) ~[aot-demo:3.0.4]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:210) ~[aot-demo:3.0.4]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:183) ~[aot-demo:3.0.4]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:161) ~[aot-demo:3.0.4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:578) ~[aot-demo:6.0.6]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[aot-demo:3.0.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[aot-demo:3.0.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[aot-demo:3.0.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[aot-demo:3.0.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304) ~[aot-demo:3.0.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293) ~[aot-demo:3.0.4]
	at com.example.application.AotDemoApplication.main(AotDemoApplication.java:11) ~[aot-demo:na]
Caused by: java.lang.IllegalStateException: Parent resource of [file:///resources!/com/example/application/AotDemoApplication$$SpringCGLIB$$0.class] not found in the resources!
	at com.vaadin.flow.spring.VaadinServletContextInitializer$CustomResourceLoader.collectResources(VaadinServletContextInitializer.java:847) ~[na:na]
	at com.vaadin.flow.spring.VaadinServletContextInitializer$CustomResourceLoader.getResources(VaadinServletContextInitializer.java:817) ~[na:na]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:422) ~[aot-demo:6.0.6]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:317) ~[aot-demo:6.0.6]
	at java.base@19.0.1/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
	at java.base@19.0.1/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
	at java.base@19.0.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[aot-demo:na]
	at java.base@19.0.1/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[aot-demo:na]
	at java.base@19.0.1/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[aot-demo:na]
	at java.base@19.0.1/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[aot-demo:na]
	at java.base@19.0.1/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[aot-demo:na]
	at com.vaadin.flow.spring.VaadinServletContextInitializer$VaadinAppShellContextListener.failFastContextInitialized(VaadinServletContextInitializer.java:556) ~[na:na]
	at com.vaadin.flow.spring.VaadinServletContextInitializer$FailFastServletContextListener.contextInitialized(VaadinServletContextInitializer.java:187) ~[aot-demo:na]
	... 41 common frames omitted

```

### Minimal reproducible example
```
npx @hilla/cli init hello
cd hello
rm src/main/resources/application.properties
mvn -Pnative  clean package native:compile -Pproduction
target/hello
```

Because of #810 you might need to add a bean used in the endpoint

### Expected behavior
When no whitelisted or blacklisted packages are defined, all packages are scanned and everything alway works, although it might be a bit slower to compile.

### Versions:
    - Vaadin / Hilla version: 2.0

**Comment by mcollovati** [comment]
This might have been fixed by vaadin/flow#17088.
