### ISSUE TITLE
Unable to start app on Windows

### ISSUE THREAD

**Issue by simasch** [vaadin/hilla#926]
I tried to upgrade on of my apps from 2.0.0 to 2.0.5 but now I can no longer run the app and get this exception:

```
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///C:/Users/simon/Workspace/simasch/fullstack-is-dead/hilla/target/classes/
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[na:na]
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[na:na]
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[na:na]
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[na:na]
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232) ~[na:na]
	at java.base/java.nio.file.Path.resolve(Path.java:515) ~[na:na]
	at dev.hilla.engine.EngineConfiguration.getOpenAPIFile(EngineConfiguration.java:160) ~[engine-core-2.0.0.jar:na]
	at dev.hilla.engine.ParserProcessor.<init>(ParserProcessor.java:39) ~[engine-core-2.0.0.jar:na]
	at dev.hilla.internal.TaskGenerateOpenAPIImpl.execute(TaskGenerateOpenAPIImpl.java:68) ~[engine-runtime-2.0.0.jar:na]
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:301) ~[flow-server-24.0.0.jar:24.0.0]
	at com.vaadin.base.devserver.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:372) ~[vaadin-dev-server-24.0.0.jar:na]
	at com.vaadin.base.devserver.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:313) ~[vaadin-dev-server-24.0.0.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[na:na]

```

**Comment by tarekoraby** [comment]
I cannot reproduce on Windows on a freshly downloaded project + Java 17.

**Comment by Artur-** [comment]
This looks like the bug present in 2.0.4 but fixed in 2.0.5: https://github.com/vaadin/flow/issues/16605

**Comment by simasch** [comment]
In the meanwhile, I was able to make it work.
It was essential to clean node_modules and to start outside of IntelliJ.
So I assume it's an issue related to IntelliJ

**Comment by Artur-** [comment]
The mentioned Flow bug was relevant only when running without launching `prepare-frontend`. Not sure why it would be in 2.0.5
